#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PPerl
version:      0.24
version_from: PPerl.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
