#!perl -w
use strict;


open(PPERL, ">pperl.h") || die "Can't write to pperl.h: $!";
open(PPERL_HEAD, "<pperl.h.header") || die "Can't read pperl.h.header: $!";
open(PPERL_FOOT, "<pperl.h.footer") || die "Can't read pperl.h.footer: $!";

print PPERL <<'EOT';
/* pperl.h */

#define perl_header ""\
EOT

while (<PPERL_HEAD>) {
    s/\\/\\\\/g; # double up all backslashes
    s/"/\\"/g; # backslash all quotes
    s/^(.*)$/"$1\\n"\\/; # wrap in quotes
    print PPERL $_;
}

print PPERL << 'EOT';
"\n"

#define perl_footer ""\
EOT

while (<PPERL_FOOT>) {
    s/\\/\\\\/g; # double up all backslashes
    s/"/\\"/g; # backslash all quotes
    s/^(.*)$/"$1\\n"\\/; # wrap in quotes
    print PPERL $_;
}

print PPERL << 'EOT';
"\n"

EOT

print PPERL '#define PPERL_VERSION "'. `grep 'VERSION =' PPerl.pm | cut -d"'" -f2` . "\"\n";
close PPERL;
close PPERL_HEAD;
close PPERL_FOOT;
